### ISSUE TITLE
read permissions not OK for config file at /home/lmanyonho/fixmystreet/script/../commonlib/perllib/mySociety/Config.pm line 80.

### ISSUE THREAD

**Issue by lmanyonho** [mysociety/commonlib#40]
Hi guys I am having an issue while trying to install fixmystret on vagrant in ubuntu 12.04 and the problem is as described above and the line of code being referred to is

# read_config_from_php
# Read configuration data from the named PHP configuration file
sub read_config_from_php($) {
    my ($f) = @_;

    if (! -r $f) {
        throw Error::Simple "$f: read permissions not OK for config file";
    }

**Comment by dracos** [comment]
This means the user running the script does not have permission to read the file; you need to run the script as a user that can access the conf/general.yml file. This is not an issue with the code, I'm afraid.
