### ISSUE TITLE
Error updating APT sources

### ISSUE THREAD

**Issue by gbp** [mysociety/commonlib#73]
When building a fresh Vagrant box I am seeing:

```
Updating APT sources...
/home/vagrant/alaveteli/commonlib/bin/install-site.sh: 167: [: false: unexpected operator
```

https://github.com/mysociety/commonlib/blob/02fa7555ad5852fe929d0f093879469e5819fccf/bin/install-site.sh#L167

**Comment by dracos** [comment]
Which OS is it running on?

**Comment by dracos** [comment]
Anyway, doesn't matter, that's not valid sh with two equals.

**Comment by dracos** [comment]
The other ifs in #70 were okay, but this one should probably be `if [ x"$BACKPORTS" = x"true" ]` to match.
