### ISSUE TITLE
Install script should warn rather than error for unsupported OS when setting up APT repositories

### ISSUE THREAD

**Issue by sagepe** [mysociety/commonlib#87]
This is more friendly for re-users who might want to test using an OS we haven't formally added support for.

**Comment by gbp** [comment]
Would be good for https://github.com/mysociety/alaveteli/issues/6342

**Comment by sagepe** [comment]
Im going to add Bookworm and Jammy and potentially remove Buster, Xenial and Bionic at the same time.

**Comment by sagepe** [comment]
I'm also going to switch the source to the newer [deb882 format](https://manpages.debian.org/unstable/apt/sources.list.5.en.html#DEB822-STYLE_FORMAT), as this is supported on all the distros we now care about.

This includes removing the call to `apt-key`, which is deprecated, in place of storing the key in the filesystem and using `Signed-By:` in the sources configuration.
